#!/bin/sh

# check args count
if [ $# -ne 1 ]; then
  echo "Usage : $0 <kickstart file>"
  exit
fi

# check require packages
reqpkgs="anaconda lorax python-six"
ninstpkgs=""
cnt=0

for pkg in ${reqpkgs}
do
  rpm -q ${pkg} > /dev/null
  if [ $? -ne 0 ]; then
    ninstpkgs="${ninstpkgs}${pkg} "
    cnt=`expr ${cnt} "+" 1`
  fi
done

if [ ${cnt} -ne 0 ]; then
  echo "require packages: ${ninstpkgs}"
  exit
fi

# check kickstart files
kickstart=${1}
if [ ! -f ${kickstart} ]; then
  echo "${kickstart} is not exist."
  exit
fi

logfile=${0}-`date +%Y%m%d%H%M%S`.log
temp=tmp
release=release
imgfile=CentOS-Userland-7-armhfp-RPi4-WebUI-2003.raw.img

mountpt=mnt
logdir=logs
sysimage=${mountpt}/sysimage
bootfs=${mountpt}/bootfs
bootraw=${mountpt}/bootraw

if [ ! -d ${mountpt} ]; then
  mkdir -p ${sysimage} ${bootfs} ${bootraw}
fi

if [ ! -d ${temp} ]; then
  mkdir -p ${temp}
fi

if [ ! -d {logdir} ]; then
  mkdir -p ${logdir}
fi

if [ -d ${release} ]; then
  rm -rf ${release}
fi

livemedia-creator \
--ks ${kickstart} \
--no-virt \
--image-only \
--keep-image \
--make-disk \
--logfile=${logdir}/${logfile} \
--tmp=${temp} --resultdir ${release} \
--image-name=${imgfile}

ret=$?
if [ ${ret} -ne 0 ]; then
  echo "livemedia-creator is failed"
  exit
fi

lobootfs=$(kpartx -avs ${release}/${imgfile} | awk 'NR==1 {print $3}')
echo ${loopdev}
lodev=$(losetup | grep ${imgfile} | awk '{print $1}')
echo ${lodev}

dd if=/dev/mapper/${lobootfs} of=${release}/${lobootfs}.raw.img bs=1M


parted ${lodev} -s rm 1 -s mkpart primary fat16 1.00MiB 101MiB -s set 1 boot on
kpartx -uvs /dev/${lodev}

mkfs.vfat -c -v /dev/mapper/${lobootfs}
fsck.vfat /dev/mapper/${lobootfs}

vfatuuid=$(blkid /dev/mapper/${lobootfs} | awk -F\" '{ print $4 }')
echo ${vfatuuid}

mount /dev/mapper/${lobootfs} ${bootfs}
mount ${release}/${lobootfs}.raw.img ${bootraw}
mount /dev/mapper/loop0p2 ${sysimage}

cp -aR ${bootraw}/. ${bootfs}
#sed -i".orig" "s/mmcblk0p/sda/" mnt/bootfs/cmdline.txt

sed -i".orig" -e "/boot/c\UUID=${vfatuuid}                            \/boot                   vfat    defaults,noatime 0 0" -e 's/\(defaults\).*/defaults,noatime 0 0/g' mnt/sysimage/etc/fstab

cat mnt/sysimage/etc/fstab

umount mnt/*
rm -f ${release}/${lobootfs}.raw.img

kpartx -dvs ${release}/${imgfile}
